language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: clicker-angular
  api_key:
    secure: U+7Vnq5zml51ie81cFlaKTb2piKM8fZaFjOdUnTbPH6YSF9V5TukKpJyq8M1zDOgyBnYZvlFlyI37AghuEr5PMlf16KEA1f/8KhZIhGaBqi2hlwHo3XV1LqEblqKoOUMNPjHp7v4WVqBMRrL76jpvvrnJJFvJY5cFEc5mTCz0X9SQVGrvHYxIx7jNsvtcR0iP5FNZm9OX2Yg85BsITWmvPE+iucLu8m4c9rl3bxdbPVBHF4T84foMbdh4XMth/QADcS19fZUpmBsk5JDR2qYtpmpFDeVYlRSSg++5aqg437dGLJfXM9eMaAq+Zo/WuRQB4yeVkIEsGfVtXMUe7r98MCGbmNg3fLpu5miUZLEsutXHGKkGuE8Pdm1HZaq7ru9Dt/YvhB0coz0ZNFUShw6yQ/Y/s5K09O9HlXZmEgQ9zs9BPaZgHJ1+dD9cRoHNj7h8gA5KcHbBVbvuDN78WMApkbeqiaXHTSEX8TRKj1qDsdGe4G2/DoeQCwkJYzZPIn8+nV35pUlZIMsIAFCYVDceJVfjquJNNOR6EDZ2RDzEdhuwOr/lpH4wNmC6Q1QQaMc3t5lydXiopOLJh3vzgh//skLByCvrD7pEyrDXfeYAANp/C6l8ON2pxmo6Ie+5XcXx0QDJ7JUe7qd784yPUNrNctuCdtULEQ1G485LxVwpxw=

